version: "3.3"

services:
  php:
    build:
      dockerfile: deploy/docker/Php.Dockerfile
      context: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./project:/var/www/html

  nginx:
    image: nginx:1.27.3
    volumes:
      - ./project:/var/www/html
      - ./deploy/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deploy/nginx/logs:/var/log/nginx
    restart: unless-stopped
    ports:
      - "$APP_PORT:80"

  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_ROOT_PASSWORD: $DB_PASS
    ports:
      - '$DB_PORT:3306'
    volumes:
      - ./deploy/db:/var/lib/mysql