services:
  nginx:
    image: nginx:1.27.3
    restart: unless-stopped
    links:
      - php
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./deploy/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./project:/var/www/html
      - ./deploy/nginx/logs:/var/log/nginx/
    depends_on:
      - php
    networks:
      - pet-network

  php:
    container_name: php
    build:
      dockerfile: ./deploy/docker/Php.Dockerfile
      context: ./
    restart: unless-stopped
    expose:
      - 9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '127.0.0.1:${PHP_PORT}:9000'
    volumes:
      - ./project:/var/www/html
    networks:
      - pet-network
    env_file:
      - .env

  mysql:
    image: mysql:9
    restart: unless-stopped
    volumes:
      - ./deploy/db/data:/var/lib/mysql
      - ./deploy/db/my.cnf:/etc/alternatives/my.cnf
    ports:
      - '${DB_PORT}:3306'
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASS}'
    networks:
      - pet-network

  redis:
    image: redis:6
    ports:
      - '${REDIS_PORT}:6379'
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    restart: unless-stopped
    networks:
      - pet-network

  ws:
    build:
      dockerfile: ./deploy/docker/Node.Dockerfile
      context: ./
    restart: unless-stopped
    ports:
      - "${WS_SERVER_PORT}:80"
    networks:
      - pet-network

networks:
  pet-network:
    driver: bridge